export default {
    navbar: 'Navbar',
    home: 'Home',
    about: 'About',
    services: 'Services',
    dropdown: 'Dropdown',
    content: 'Content',
    demo: 'Demo',
    button: 'Click',
    links: 'Links',
    link1: 'Link 1',
    link2: 'Link 2',
    link3: 'Link 2',
    footer: 'Footer Content',
    text: ' Here you can use rows and columns here to organize your footer content',
    apiUrl: 'https://courier.digitalvichar.in/api/v1/',
    headers: {
        token: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNTkzNjY5NDA3LCJleHAiOjE1OTM2NzY2MDd9.Vi8KOhAvqJhg8BbZuBHwTqr7v-CSmQsHgvnJwVhJVos',
        apikey: 'courierservice-0000-9876-5432-10@@',
        'Access-Control-Allow-Origin': true
    },
    add: 'Add',
    addZone: 'Add Zone',
    code: 'Code',
    name: 'Name',
    permit: 'Permit',
    document_name: 'Document_Name',
    commission_type: 'Commission_Type',
    commission_value: 'Commission_Value',
    applicable_on: 'Applicable_On',
    save: 'Save',
    edit: 'Update',
    operation: 'Operation',
    list: 'List',
    login: 'Login'
}